Traceback (most recent call last):
  File "/home/prabhasyadav/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/prabhasyadav/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/prabhasyadav/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/prabhasyadav/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/prabhasyadav/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/prabhasyadav/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/prabhasyadav/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/prabhasyadav/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
p1 = pn.pane.Markdown("""
### Python popularity
""")

p2 = pn.pane.PNG("images/bg1_f1.png", width=500) 

p3= pn.pane.Markdown("""</br></br></br>

+ _Python_ has become a mainstream computing language. 
+ Details of the plot are [here](shorturl.at/htwQ7). 
+ This all means - it is good to learn to code in _Python_
""")

p4 = pn.Column(p1,p2)

pn.Row(p4, p3)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-4e8bdb08145d>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m p1 = pn.pane.Markdown("""
[0m[1;32m      2[0m [0;31m### Python popularity[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m """)
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mp2[0m [0;34m=[0m [0mpn[0m[0;34m.[0m[0mpane[0m[0;34m.[0m[0mPNG[0m[0;34m([0m[0;34m"images/bg1_f1.png"[0m[0;34m,[0m [0mwidth[0m[0;34m=[0m[0;36m500[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'pn' is not defined
NameError: name 'pn' is not defined

